### ISSUE TITLE
NoSuchElementException: next on empty iterator

### ISSUE THREAD

**Issue by patriknw** [typesafehub/ghpullrequest-validator#61]
```
    ERROR] [01/23/2014 11:09:59.918] [default-akka.actor.default-dispatcher-94112] [akka://default/user/ghpr-2/akka+akka/pull-request-checker] next on empty iterator
    java.util.NoSuchElementException: next on empty iterator
            at scala.collection.Iterator$$anon$2.next(Iterator.scala:39)
            at scala.collection.Iterator$$anon$2.next(Iterator.scala:37)
            at scala.collection.IndexedSeqLike$Elements.next(IndexedSeqLike.scala:64)
            at scala.collection.IterableLike$class.head(IterableLike.scala:91)
            at scala.collection.mutable.ArrayOps$ofRef.scala$collection$IndexedSeqOptimized$$super$head(ArrayOps.scala:105)
            at scala.collection.IndexedSeqOptimized$class.head(IndexedSeqOptimized.scala:120)
            at scala.collection.mutable.ArrayOps$ofRef.head(ArrayOps.scala:105)
            at scala.collection.TraversableLike$class.last(TraversableLike.scala:455)
            at scala.collection.mutable.ArrayOps$ofRef.scala$collection$IndexedSeqOptimized$$super$last(ArrayOps.scala:105)
            at scala.collection.IndexedSeqOptimized$class.last(IndexedSeqOptimized.scala:126)
            at scala.collection.mutable.ArrayOps$ofRef.last(ArrayOps.scala:105)
            at backend.PullRequestChecker$$anonfun$backend$PullRequestChecker$$checkPullRequest$1.apply(PullRequestChecker.scala:226)
            at backend.PullRequestChecker$$anonfun$backend$PullRequestChecker$$checkPullRequest$1.apply(PullRequestChecker.scala:225)
            at scala.collection.immutable.List.foreach(List.scala:318)
            at backend.PullRequestChecker.backend$PullRequestChecker$$checkPullRequest(PullRequestChecker.scala:225)
            at backend.PullRequestChecker$$anonfun$receive$1.applyOrElse(PullRequestChecker.scala:47)
            at akka.actor.ActorCell.receiveMessage(ActorCell.scala:498)
            at akka.actor.ActorCell.invoke(ActorCell.scala:456)
            at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:237)
            at akka.dispatch.Mailbox.run(Mailbox.scala:219)
            at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:386)
            at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:262)
            at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:975)
            at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1478)
            at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:104)
```

**Comment by thangaswamyarun** [comment]
Is this issue have been resolved?
